/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTodoModal: typeof import('./src/components/AddTodoModal.vue')['default']
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PaginationControl: typeof import('./src/components/PaginationControl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    WelcomPage: typeof import('./src/components/WelcomPage.vue')['default']
  }
}
